apiVersion: v1
kind: Pod
metadata:
  name: multus-pod-demo
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf 
spec:
  containers:
  - name: multus-pod-demo 
    command: ["/bin/bash", "-c", "sleep infinity"]
    image: quay.io/wcaban/net-toolbox